language: python
python:
    - 3.4
    - 3.5
services:
    - postgresql

install:
    - pip install -r requirements_test.txt

before_script:
    - psql -U postgres -c "create database nestedworld_tests"
    - psql -U postgres -c "create extension postgis"
    - python manage.py resetdb

script: DATABASE_URL="postgresql://postgres@localhost/nestedworld_tests" nosetests --with-coverage --cover-package nestedworld_api,flask_guimauve

after_success:
    - coveralls
